version: '3'
services:
  go:
    container_name: "go-practice"
    build: ./build/
    ports:
      - 8080:8080
    volumes:
      - ./cmd:/go/src/cmd
    env_file:
      - ./build/.go_env
    tty: true
    
